# -*- coding: utf-8 -*-
"""Assignment -1 (1).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e_1IZFNTmCXhJz8Zt7sBBBZ_4WQUpc11

1. Write a program which will find all such numbers which are divisible by 7 but are not a multiple of 5, between 2000 and 3200 (both included). The numbers obtained should be printed in a comma-separated sequence on a single line.
"""

for i in range(2000,3201):
  if(i%7==0 and i%5!=0):
    print(i,end=",")

"""2. Write a Python program to accept the user's first and last name and then getting them printed in the the reverse order with a space between first name and last name"""

first_name=input("enter first name")
last_name=input("enter last name")
print(first_name[::-1]+" "+last_name[::-1])

"""3.Write a Python program to find the volume of a sphere with diameter 12 cm.  
 
Formula: V=4/3 * π * r 3
"""

def vol():
  d=12
  vol=4/3*3.14*(d/2)**3
  print("volume of sphere ",vol,"cm³")
vol()

"""4.Write a program which accepts a sequence of comma-separated numbers from console and generate a list."""

l=[]
n=int(input("enter the size of list"))
for i in range(n):
  s=int(input("enter numbers "))
  l.append(s)
print(l)

"""5. Create the below pattern using nested for loop in Python. 
 
 
*  
* *  
* * * 
* * * *  
* * * * *  
* * * *  
* * *  
* *  
*
"""



"""6. Write a Python program to reverse a word after accepting the input from the user. 
 
Sample Output: 
 
Input word: iNeuron 
 
Output: norueNi
"""

string=input("enter the word to be reversed")
print(string[::-1])

"""7. Write a Python Program to print the given string in the format specified in the ​sample output. 
 WE, THE PEOPLE OF INDIA, having solemnly resolved to constitute India into a SOVEREIGN, SOCIALIST, SECULAR, DEMOCRATIC REPUBLIC and to secure to all its citizens 
 
Sample Output: 
 
WE, THE PEOPLE OF INDIA,   having solemnly resolved to constitute India into a SOVEREIGN, !  SOCIALIST, SECULAR, DEMOCRATIC REPUBLIC    and to secure to all its citizens
"""

s="WE, THE PEOPLE OF INDIA, having solemnly resolved to constitute India into a SOVEREIGN, SOCIALIST, SECULAR, DEMOCRATIC REPUBLIC and to secure to all its citizens"
st=""
l=s.split(" ")
print(l)
for i in l:
  if i=="SOCIALIST,":
    st=st+"!"+i
  else:
    st=st+" "+i
print(st)

"""Note : - NOTE:​ ​The​ ​solution​ ​shared​ ​through​ ​Github​ ​should​ ​contain​ ​the​ ​source code​ ​used​ ​ and​  ​the​ ​output"""

